"""add fielding game lines and season stats by position

Revision ID: 1ea36f0077a6
Revises: f9e7be5c6154
Create Date: 2026-08-10 22:26:01.605782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ea36f0077a6'
down_revision: Union[str, Sequence[str], None] = 'f9e7be5c6154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fielding_game_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_season_id', sa.Integer(), nullable=False),
    sa.Column('team_season_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('appearances', sa.Integer(), nullable=False),
    sa.Column('po', sa.Integer(), nullable=False),
    sa.Column('a', sa.Integer(), nullable=False),
    sa.Column('e', sa.Integer(), nullable=False),
    sa.Column('dp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_season_id'], ['player_seasons.id'], ),
    sa.ForeignKeyConstraint(['team_season_id'], ['team_seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_season_id', 'position')
    )
    op.create_index(op.f('ix_fielding_game_lines_game_id'), 'fielding_game_lines', ['game_id'], unique=False)
    op.create_index(op.f('ix_fielding_game_lines_player_season_id'), 'fielding_game_lines', ['player_season_id'], unique=False)
    op.create_index(op.f('ix_fielding_game_lines_position'), 'fielding_game_lines', ['position'], unique=False)
    op.create_index(op.f('ix_fielding_game_lines_team_season_id'), 'fielding_game_lines', ['team_season_id'], unique=False)
    op.create_table('fielding_season_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_season_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('games', sa.Integer(), nullable=False),
    sa.Column('appearances', sa.Integer(), nullable=False),
    sa.Column('po', sa.Integer(), nullable=False),
    sa.Column('a', sa.Integer(), nullable=False),
    sa.Column('e', sa.Integer(), nullable=False),
    sa.Column('dp', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_season_id'], ['player_seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_season_id', 'position')
    )
    op.create_index(op.f('ix_fielding_season_stats_player_season_id'), 'fielding_season_stats', ['player_season_id'], unique=False)
    op.create_index(op.f('ix_fielding_season_stats_position'), 'fielding_season_stats', ['position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fielding_season_stats_position'), table_name='fielding_season_stats')
    op.drop_index(op.f('ix_fielding_season_stats_player_season_id'), table_name='fielding_season_stats')
    op.drop_table('fielding_season_stats')
    op.drop_index(op.f('ix_fielding_game_lines_team_season_id'), table_name='fielding_game_lines')
    op.drop_index(op.f('ix_fielding_game_lines_position'), table_name='fielding_game_lines')
    op.drop_index(op.f('ix_fielding_game_lines_player_season_id'), table_name='fielding_game_lines')
    op.drop_index(op.f('ix_fielding_game_lines_game_id'), table_name='fielding_game_lines')
    op.drop_table('fielding_game_lines')
    # ### end Alembic commands ###
