"""Add cross-division strength offsets

Revision ID: 2eaa2df25e10
Revises: 4feef74e8c15
Create Date: 2026-08-12 18:47:50.343216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eaa2df25e10'
down_revision: Union[str, Sequence[str], None] = '4feef74e8c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('division_strength',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('offset', sa.Float(), nullable=True),
    sa.Column('standard_error', sa.Float(), nullable=True),
    sa.Column('adjustment', sa.Float(), nullable=True),
    sa.Column('adjustment_se', sa.Float(), nullable=True),
    sa.Column("bridge_players", sa.Integer(), nullable=False, server_default="0"),
    sa.Column("bridge_pa", sa.Float(), nullable=False, server_default="0"),
    sa.Column('scale', sa.Float(), nullable=True),
    sa.Column("identifying_players", sa.Integer(), nullable=False, server_default="0"),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_division_strength_division_id'), 'division_strength', ['division_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_division_strength_division_id'), table_name='division_strength')
    op.drop_table('division_strength')
    # ### end Alembic commands ###
