"""Store the playing-time prior pivot so the curve is recoverable

Revision ID: 3cf33237cd34
Revises: a0878f0d16c9
Create Date: 2026-08-12 22:30:45.468471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cf33237cd34'
down_revision: Union[str, Sequence[str], None] = 'a0878f0d16c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batting_true_talent', sa.Column('prior_center_log_pa', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batting_true_talent', 'prior_center_log_pa')
    # ### end Alembic commands ###
