"""Add remaining fixtures to team strength

Revision ID: 4feef74e8c15
Revises: e8e0f6047d5d
Create Date: 2026-08-12 18:07:29.248759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4feef74e8c15'
down_revision: Union[str, Sequence[str], None] = 'e8e0f6047d5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default is required, not cosmetic: the model's default is
    # Python-side only, and SQLite refuses to add a NOT NULL column to
    # existing rows without one. Existing rows land on 0 and are corrected by
    # the next recompute, which is safe — 0 remaining fixtures is exactly
    # right for every completed season.
    op.add_column(
        'team_strength',
        sa.Column('games_remaining', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column('team_strength', sa.Column('sos_remaining', sa.Float(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_strength', 'sos_remaining')
    op.drop_column('team_strength', 'games_remaining')
    # ### end Alembic commands ###
