"""add fielding stats to batting_season_stats

Revision ID: 541b9a2791f0
Revises: a7c491cc751a
Create Date: 2026-07-04 23:00:12.521625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '541b9a2791f0'
down_revision: Union[str, Sequence[str], None] = 'a7c491cc751a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batting_season_stats', sa.Column('field_po', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('batting_season_stats', sa.Column('field_a', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('batting_season_stats', sa.Column('field_e', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('batting_season_stats', sa.Column('field_dp', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batting_season_stats', 'field_dp')
    op.drop_column('batting_season_stats', 'field_e')
    op.drop_column('batting_season_stats', 'field_a')
    op.drop_column('batting_season_stats', 'field_po')
    # ### end Alembic commands ###
