"""add risp splits and game lob

Revision ID: 59e6cc2d0d86
Revises: 541b9a2791f0
Create Date: 2026-07-04 23:35:09.373465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59e6cc2d0d86'
down_revision: Union[str, Sequence[str], None] = '541b9a2791f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batting_game_lines', sa.Column('risp_ab', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('batting_game_lines', sa.Column('risp_h', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('batting_season_stats', sa.Column('risp_ab', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('batting_season_stats', sa.Column('risp_h', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('games', sa.Column('home_lob', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_lob', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'away_lob')
    op.drop_column('games', 'home_lob')
    op.drop_column('batting_season_stats', 'risp_h')
    op.drop_column('batting_season_stats', 'risp_ab')
    op.drop_column('batting_game_lines', 'risp_h')
    op.drop_column('batting_game_lines', 'risp_ab')
    # ### end Alembic commands ###
