"""add catcher steals-against columns to fielding tables

Revision ID: 9de866620f94
Revises: 1ea36f0077a6
Create Date: 2026-08-11 20:15:31.777002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9de866620f94'
down_revision: Union[str, Sequence[str], None] = '1ea36f0077a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default='0' is required, not cosmetic: these tables already hold
    # rows, and SQLite rejects a NOT NULL column added without a default.
    # Existing rows are backfilled to 0 and then rewritten with real values by
    # re-running the box-score scrape and stats.recompute (the same
    # reprocess-from-cache path the fielding tables were first populated by).
    for table in ('fielding_game_lines', 'fielding_season_stats'):
        for column in ('sba', 'csb', 'pb'):
            op.add_column(
                table, sa.Column(column, sa.Integer(), nullable=False, server_default='0')
            )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fielding_season_stats', 'pb')
    op.drop_column('fielding_season_stats', 'csb')
    op.drop_column('fielding_season_stats', 'sba')
    op.drop_column('fielding_game_lines', 'pb')
    op.drop_column('fielding_game_lines', 'csb')
    op.drop_column('fielding_game_lines', 'sba')
    # ### end Alembic commands ###
