"""Shrink batters toward a playing-time-aware prior

Revision ID: a0878f0d16c9
Revises: 2eaa2df25e10
Create Date: 2026-08-12 22:09:25.496447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0878f0d16c9'
down_revision: Union[str, Sequence[str], None] = '2eaa2df25e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batting_true_talent', sa.Column('prior_woba', sa.Float(), nullable=True))
    op.add_column('batting_true_talent', sa.Column('shrunk_woba_sd', sa.Float(), nullable=True))
    op.add_column('batting_true_talent', sa.Column('prior_ln_pa_slope', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batting_true_talent', 'prior_ln_pa_slope')
    op.drop_column('batting_true_talent', 'shrunk_woba_sd')
    op.drop_column('batting_true_talent', 'prior_woba')
    # ### end Alembic commands ###
