"""initial schema

Revision ID: a7c491cc751a
Revises: 
Create Date: 2026-07-04 09:46:19.747000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7c491cc751a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('is_senior', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leagues_code'), 'leagues', ['code'], unique=True)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('bats', sa.String(), nullable=True),
    sa.Column('throws', sa.String(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_full_name'), 'players', ['full_name'], unique=False)
    op.create_index(op.f('ix_players_source_id'), 'players', ['source_id'], unique=True)
    op.create_table('scrape_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('cache_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_log_entity_type'), 'scrape_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_scrape_log_source_id'), 'scrape_log', ['source_id'], unique=False)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seasons_year'), 'seasons', ['year'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=True)
    op.create_table('league_seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('source_tournament_id', sa.Integer(), nullable=False),
    sa.Column('competition_slug', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'season_id')
    )
    op.create_index(op.f('ix_league_seasons_league_id'), 'league_seasons', ['league_id'], unique=False)
    op.create_index(op.f('ix_league_seasons_season_id'), 'league_seasons', ['season_id'], unique=False)
    op.create_index(op.f('ix_league_seasons_source_tournament_id'), 'league_seasons', ['source_tournament_id'], unique=True)
    op.create_table('league_season_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_season_id', sa.Integer(), nullable=False),
    sa.Column('lg_obp', sa.Float(), nullable=True),
    sa.Column('lg_slg', sa.Float(), nullable=True),
    sa.Column('lg_woba', sa.Float(), nullable=True),
    sa.Column('lg_era', sa.Float(), nullable=True),
    sa.Column('lg_fip', sa.Float(), nullable=True),
    sa.Column('fip_constant', sa.Float(), nullable=True),
    sa.Column('runs_per_pa', sa.Float(), nullable=True),
    sa.Column('runs_per_win', sa.Float(), nullable=True),
    sa.Column('replacement_runs_per_pa', sa.Float(), nullable=True),
    sa.Column('replacement_fip_delta', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['league_season_id'], ['league_seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_league_season_context_league_season_id'), 'league_season_context', ['league_season_id'], unique=True)
    op.create_table('team_seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('league_season_id', sa.Integer(), nullable=False),
    sa.Column('source_team_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('short_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['league_season_id'], ['league_seasons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_season_id', 'source_team_id')
    )
    op.create_index(op.f('ix_team_seasons_league_season_id'), 'team_seasons', ['league_season_id'], unique=False)
    op.create_index(op.f('ix_team_seasons_source_team_id'), 'team_seasons', ['source_team_id'], unique=False)
    op.create_index(op.f('ix_team_seasons_team_id'), 'team_seasons', ['team_id'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('league_season_id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=True),
    sa.Column('home_team_season_id', sa.Integer(), nullable=False),
    sa.Column('away_team_season_id', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['away_team_season_id'], ['team_seasons.id'], ),
    sa.ForeignKeyConstraint(['home_team_season_id'], ['team_seasons.id'], ),
    sa.ForeignKeyConstraint(['league_season_id'], ['league_seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_game_date'), 'games', ['game_date'], unique=False)
    op.create_index(op.f('ix_games_league_season_id'), 'games', ['league_season_id'], unique=False)
    op.create_index(op.f('ix_games_source_id'), 'games', ['source_id'], unique=True)
    op.create_table('player_seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_season_id', sa.Integer(), nullable=False),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('position_primary', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_season_id'], ['team_seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'team_season_id')
    )
    op.create_index(op.f('ix_player_seasons_player_id'), 'player_seasons', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_seasons_team_season_id'), 'player_seasons', ['team_season_id'], unique=False)
    op.create_table('batting_game_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_season_id', sa.Integer(), nullable=False),
    sa.Column('team_season_id', sa.Integer(), nullable=False),
    sa.Column('pa', sa.Integer(), nullable=False),
    sa.Column('ab', sa.Integer(), nullable=False),
    sa.Column('r', sa.Integer(), nullable=False),
    sa.Column('h', sa.Integer(), nullable=False),
    sa.Column('doubles', sa.Integer(), nullable=False),
    sa.Column('triples', sa.Integer(), nullable=False),
    sa.Column('hr', sa.Integer(), nullable=False),
    sa.Column('rbi', sa.Integer(), nullable=False),
    sa.Column('bb', sa.Integer(), nullable=False),
    sa.Column('ibb', sa.Integer(), nullable=False),
    sa.Column('hbp', sa.Integer(), nullable=False),
    sa.Column('so', sa.Integer(), nullable=False),
    sa.Column('sf', sa.Integer(), nullable=False),
    sa.Column('sh', sa.Integer(), nullable=False),
    sa.Column('sb', sa.Integer(), nullable=False),
    sa.Column('cs', sa.Integer(), nullable=False),
    sa.Column('gdp', sa.Integer(), nullable=False),
    sa.Column('field_po', sa.Integer(), nullable=False),
    sa.Column('field_a', sa.Integer(), nullable=False),
    sa.Column('field_e', sa.Integer(), nullable=False),
    sa.Column('field_dp', sa.Integer(), nullable=False),
    sa.Column('field_sba', sa.Integer(), nullable=False),
    sa.Column('field_csb', sa.Integer(), nullable=False),
    sa.Column('field_pb', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_season_id'], ['player_seasons.id'], ),
    sa.ForeignKeyConstraint(['team_season_id'], ['team_seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_season_id')
    )
    op.create_index(op.f('ix_batting_game_lines_game_id'), 'batting_game_lines', ['game_id'], unique=False)
    op.create_index(op.f('ix_batting_game_lines_player_season_id'), 'batting_game_lines', ['player_season_id'], unique=False)
    op.create_index(op.f('ix_batting_game_lines_team_season_id'), 'batting_game_lines', ['team_season_id'], unique=False)
    op.create_table('batting_season_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_season_id', sa.Integer(), nullable=False),
    sa.Column('pa', sa.Integer(), nullable=False),
    sa.Column('ab', sa.Integer(), nullable=False),
    sa.Column('r', sa.Integer(), nullable=False),
    sa.Column('h', sa.Integer(), nullable=False),
    sa.Column('doubles', sa.Integer(), nullable=False),
    sa.Column('triples', sa.Integer(), nullable=False),
    sa.Column('hr', sa.Integer(), nullable=False),
    sa.Column('rbi', sa.Integer(), nullable=False),
    sa.Column('bb', sa.Integer(), nullable=False),
    sa.Column('ibb', sa.Integer(), nullable=False),
    sa.Column('hbp', sa.Integer(), nullable=False),
    sa.Column('so', sa.Integer(), nullable=False),
    sa.Column('sf', sa.Integer(), nullable=False),
    sa.Column('sh', sa.Integer(), nullable=False),
    sa.Column('sb', sa.Integer(), nullable=False),
    sa.Column('cs', sa.Integer(), nullable=False),
    sa.Column('gdp', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_season_id'], ['player_seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batting_season_stats_player_season_id'), 'batting_season_stats', ['player_season_id'], unique=True)
    op.create_table('batting_war',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_season_id', sa.Integer(), nullable=False),
    sa.Column('woba', sa.Float(), nullable=True),
    sa.Column('wraa', sa.Float(), nullable=True),
    sa.Column('war', sa.Float(), nullable=True),
    sa.Column('formula_version', sa.String(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_season_id'], ['player_seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batting_war_player_season_id'), 'batting_war', ['player_season_id'], unique=True)
    op.create_table('pitching_game_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_season_id', sa.Integer(), nullable=False),
    sa.Column('team_season_id', sa.Integer(), nullable=False),
    sa.Column('outs_recorded', sa.Integer(), nullable=False),
    sa.Column('h', sa.Integer(), nullable=False),
    sa.Column('r', sa.Integer(), nullable=False),
    sa.Column('er', sa.Integer(), nullable=False),
    sa.Column('bb', sa.Integer(), nullable=False),
    sa.Column('ibb', sa.Integer(), nullable=False),
    sa.Column('so', sa.Integer(), nullable=False),
    sa.Column('hr', sa.Integer(), nullable=False),
    sa.Column('hbp', sa.Integer(), nullable=False),
    sa.Column('bf', sa.Integer(), nullable=False),
    sa.Column('win', sa.Boolean(), nullable=False),
    sa.Column('loss', sa.Boolean(), nullable=False),
    sa.Column('save', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_season_id'], ['player_seasons.id'], ),
    sa.ForeignKeyConstraint(['team_season_id'], ['team_seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_season_id')
    )
    op.create_index(op.f('ix_pitching_game_lines_game_id'), 'pitching_game_lines', ['game_id'], unique=False)
    op.create_index(op.f('ix_pitching_game_lines_player_season_id'), 'pitching_game_lines', ['player_season_id'], unique=False)
    op.create_index(op.f('ix_pitching_game_lines_team_season_id'), 'pitching_game_lines', ['team_season_id'], unique=False)
    op.create_table('pitching_season_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_season_id', sa.Integer(), nullable=False),
    sa.Column('outs_recorded', sa.Integer(), nullable=False),
    sa.Column('h', sa.Integer(), nullable=False),
    sa.Column('r', sa.Integer(), nullable=False),
    sa.Column('er', sa.Integer(), nullable=False),
    sa.Column('bb', sa.Integer(), nullable=False),
    sa.Column('ibb', sa.Integer(), nullable=False),
    sa.Column('so', sa.Integer(), nullable=False),
    sa.Column('hr', sa.Integer(), nullable=False),
    sa.Column('hbp', sa.Integer(), nullable=False),
    sa.Column('bf', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_season_id'], ['player_seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pitching_season_stats_player_season_id'), 'pitching_season_stats', ['player_season_id'], unique=True)
    op.create_table('pitching_war',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_season_id', sa.Integer(), nullable=False),
    sa.Column('fip', sa.Float(), nullable=True),
    sa.Column('war', sa.Float(), nullable=True),
    sa.Column('formula_version', sa.String(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_season_id'], ['player_seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pitching_war_player_season_id'), 'pitching_war', ['player_season_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pitching_war_player_season_id'), table_name='pitching_war')
    op.drop_table('pitching_war')
    op.drop_index(op.f('ix_pitching_season_stats_player_season_id'), table_name='pitching_season_stats')
    op.drop_table('pitching_season_stats')
    op.drop_index(op.f('ix_pitching_game_lines_team_season_id'), table_name='pitching_game_lines')
    op.drop_index(op.f('ix_pitching_game_lines_player_season_id'), table_name='pitching_game_lines')
    op.drop_index(op.f('ix_pitching_game_lines_game_id'), table_name='pitching_game_lines')
    op.drop_table('pitching_game_lines')
    op.drop_index(op.f('ix_batting_war_player_season_id'), table_name='batting_war')
    op.drop_table('batting_war')
    op.drop_index(op.f('ix_batting_season_stats_player_season_id'), table_name='batting_season_stats')
    op.drop_table('batting_season_stats')
    op.drop_index(op.f('ix_batting_game_lines_team_season_id'), table_name='batting_game_lines')
    op.drop_index(op.f('ix_batting_game_lines_player_season_id'), table_name='batting_game_lines')
    op.drop_index(op.f('ix_batting_game_lines_game_id'), table_name='batting_game_lines')
    op.drop_table('batting_game_lines')
    op.drop_index(op.f('ix_player_seasons_team_season_id'), table_name='player_seasons')
    op.drop_index(op.f('ix_player_seasons_player_id'), table_name='player_seasons')
    op.drop_table('player_seasons')
    op.drop_index(op.f('ix_games_source_id'), table_name='games')
    op.drop_index(op.f('ix_games_league_season_id'), table_name='games')
    op.drop_index(op.f('ix_games_game_date'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_team_seasons_team_id'), table_name='team_seasons')
    op.drop_index(op.f('ix_team_seasons_source_team_id'), table_name='team_seasons')
    op.drop_index(op.f('ix_team_seasons_league_season_id'), table_name='team_seasons')
    op.drop_table('team_seasons')
    op.drop_index(op.f('ix_league_season_context_league_season_id'), table_name='league_season_context')
    op.drop_table('league_season_context')
    op.drop_index(op.f('ix_league_seasons_source_tournament_id'), table_name='league_seasons')
    op.drop_index(op.f('ix_league_seasons_season_id'), table_name='league_seasons')
    op.drop_index(op.f('ix_league_seasons_league_id'), table_name='league_seasons')
    op.drop_table('league_seasons')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_seasons_year'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_scrape_log_source_id'), table_name='scrape_log')
    op.drop_index(op.f('ix_scrape_log_entity_type'), table_name='scrape_log')
    op.drop_table('scrape_log')
    op.drop_index(op.f('ix_players_source_id'), table_name='players')
    op.drop_index(op.f('ix_players_full_name'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_leagues_code'), table_name='leagues')
    op.drop_table('leagues')
    # ### end Alembic commands ###
