"""drop unused pull tertile columns

Revision ID: b30594e1b4c3
Revises: c3a213bb0621
Create Date: 2026-07-07 21:04:45.859364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b30594e1b4c3'
down_revision: Union[str, Sequence[str], None] = 'c3a213bb0621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_season_context', 'pull_tertile_low')
    op.drop_column('league_season_context', 'pull_tertile_high')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_season_context', sa.Column('pull_tertile_high', sa.FLOAT(), nullable=True))
    op.add_column('league_season_context', sa.Column('pull_tertile_low', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
