"""add plate appearances, batter spray, matchups, first pitch strike

Revision ID: c3a213bb0621
Revises: 59e6cc2d0d86
Create Date: 2026-07-06 17:31:10.389999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3a213bb0621'
down_revision: Union[str, Sequence[str], None] = '59e6cc2d0d86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batter_pitcher_matchups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batter_player_season_id', sa.Integer(), nullable=False),
    sa.Column('pitcher_player_season_id', sa.Integer(), nullable=False),
    sa.Column('pa', sa.Integer(), nullable=False),
    sa.Column('ab', sa.Integer(), nullable=False),
    sa.Column('h', sa.Integer(), nullable=False),
    sa.Column('doubles', sa.Integer(), nullable=False),
    sa.Column('triples', sa.Integer(), nullable=False),
    sa.Column('hr', sa.Integer(), nullable=False),
    sa.Column('bb', sa.Integer(), nullable=False),
    sa.Column('so', sa.Integer(), nullable=False),
    sa.Column('hbp', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batter_player_season_id'], ['player_seasons.id'], ),
    sa.ForeignKeyConstraint(['pitcher_player_season_id'], ['player_seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batter_player_season_id', 'pitcher_player_season_id')
    )
    op.create_index(op.f('ix_batter_pitcher_matchups_batter_player_season_id'), 'batter_pitcher_matchups', ['batter_player_season_id'], unique=False)
    op.create_index(op.f('ix_batter_pitcher_matchups_pitcher_player_season_id'), 'batter_pitcher_matchups', ['pitcher_player_season_id'], unique=False)
    op.create_table('batter_spray_season_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_season_id', sa.Integer(), nullable=False),
    sa.Column('pull_count', sa.Integer(), nullable=False),
    sa.Column('center_count', sa.Integer(), nullable=False),
    sa.Column('oppo_count', sa.Integer(), nullable=False),
    sa.Column('tendency_label', sa.String(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_season_id'], ['player_seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batter_spray_season_stats_player_season_id'), 'batter_spray_season_stats', ['player_season_id'], unique=True)
    op.create_table('plate_appearances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_play_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('inning', sa.Integer(), nullable=False),
    sa.Column('half', sa.String(), nullable=False),
    sa.Column('batter_player_season_id', sa.Integer(), nullable=False),
    sa.Column('pitcher_player_season_id', sa.Integer(), nullable=True),
    sa.Column('ab', sa.Integer(), nullable=False),
    sa.Column('h', sa.Integer(), nullable=False),
    sa.Column('doubles', sa.Integer(), nullable=False),
    sa.Column('triples', sa.Integer(), nullable=False),
    sa.Column('hr', sa.Integer(), nullable=False),
    sa.Column('bb', sa.Integer(), nullable=False),
    sa.Column('ibb', sa.Integer(), nullable=False),
    sa.Column('hbp', sa.Integer(), nullable=False),
    sa.Column('so', sa.Integer(), nullable=False),
    sa.Column('sf', sa.Integer(), nullable=False),
    sa.Column('rbi', sa.Integer(), nullable=False),
    sa.Column('first_pitch_strike', sa.Boolean(), nullable=True),
    sa.Column('hitpull', sa.Integer(), nullable=True),
    sa.Column('hitdistance', sa.Integer(), nullable=True),
    sa.Column('hittype', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batter_player_season_id'], ['player_seasons.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['pitcher_player_season_id'], ['player_seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plate_appearances_batter_pitcher', 'plate_appearances', ['batter_player_season_id', 'pitcher_player_season_id'], unique=False)
    op.create_index(op.f('ix_plate_appearances_batter_player_season_id'), 'plate_appearances', ['batter_player_season_id'], unique=False)
    op.create_index(op.f('ix_plate_appearances_game_id'), 'plate_appearances', ['game_id'], unique=False)
    op.create_index(op.f('ix_plate_appearances_pitcher_player_season_id'), 'plate_appearances', ['pitcher_player_season_id'], unique=False)
    op.create_index(op.f('ix_plate_appearances_source_play_id'), 'plate_appearances', ['source_play_id'], unique=True)
    op.add_column('league_season_context', sa.Column('pull_tertile_low', sa.Float(), nullable=True))
    op.add_column('league_season_context', sa.Column('pull_tertile_high', sa.Float(), nullable=True))
    op.add_column('pitching_season_stats', sa.Column('fps_pa', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('pitching_season_stats', sa.Column('fps_strikes', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitching_season_stats', 'fps_strikes')
    op.drop_column('pitching_season_stats', 'fps_pa')
    op.drop_column('league_season_context', 'pull_tertile_high')
    op.drop_column('league_season_context', 'pull_tertile_low')
    op.drop_index(op.f('ix_plate_appearances_source_play_id'), table_name='plate_appearances')
    op.drop_index(op.f('ix_plate_appearances_pitcher_player_season_id'), table_name='plate_appearances')
    op.drop_index(op.f('ix_plate_appearances_game_id'), table_name='plate_appearances')
    op.drop_index(op.f('ix_plate_appearances_batter_player_season_id'), table_name='plate_appearances')
    op.drop_index('ix_plate_appearances_batter_pitcher', table_name='plate_appearances')
    op.drop_table('plate_appearances')
    op.drop_index(op.f('ix_batter_spray_season_stats_player_season_id'), table_name='batter_spray_season_stats')
    op.drop_table('batter_spray_season_stats')
    op.drop_index(op.f('ix_batter_pitcher_matchups_pitcher_player_season_id'), table_name='batter_pitcher_matchups')
    op.drop_index(op.f('ix_batter_pitcher_matchups_batter_player_season_id'), table_name='batter_pitcher_matchups')
    op.drop_table('batter_pitcher_matchups')
    # ### end Alembic commands ###
