"""Add team strength ratings

A new derived table only — nothing existing is altered, and like the rest of
stats/ it is safe to drop and rebuild from fact rows at any time
(stats/team_strength.py).

Revision ID: d81fb0a021de
Revises: 6ed887565a4b
Create Date: 2026-08-12 17:35:18.940022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd81fb0a021de'
down_revision: Union[str, Sequence[str], None] = '6ed887565a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_strength',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_season_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('rating_se', sa.Float(), nullable=True),
    sa.Column('sos', sa.Float(), nullable=True),
    sa.Column('expected_win_pct', sa.Float(), nullable=True),
    sa.Column('games', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('ties', sa.Integer(), nullable=False),
    sa.Column('home_advantage', sa.Float(), nullable=True),
    sa.Column('ridge_lambda', sa.Float(), nullable=True),
    sa.Column('lambda_self_calibrated', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_season_id'], ['team_seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_strength_team_season_id'), 'team_strength', ['team_season_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_strength_team_season_id'), table_name='team_strength')
    op.drop_table('team_strength')
    # ### end Alembic commands ###
