"""add batting and pitching true talent tables

Revision ID: f9e7be5c6154
Revises: b30594e1b4c3
Create Date: 2026-07-08 18:45:36.021399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9e7be5c6154'
down_revision: Union[str, Sequence[str], None] = 'b30594e1b4c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batting_true_talent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_season_id', sa.Integer(), nullable=False),
    sa.Column('pa', sa.Integer(), nullable=False),
    sa.Column('observed_woba', sa.Float(), nullable=True),
    sa.Column('shrunk_woba', sa.Float(), nullable=True),
    sa.Column('reliability', sa.Float(), nullable=True),
    sa.Column('stabilization_pa', sa.Float(), nullable=True),
    sa.Column('k_self_calibrated', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_season_id'], ['player_seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batting_true_talent_player_season_id'), 'batting_true_talent', ['player_season_id'], unique=True)
    op.create_table('pitching_true_talent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_season_id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.Float(), nullable=False),
    sa.Column('observed_fip', sa.Float(), nullable=True),
    sa.Column('shrunk_fip', sa.Float(), nullable=True),
    sa.Column('reliability', sa.Float(), nullable=True),
    sa.Column('stabilization_ip', sa.Float(), nullable=True),
    sa.Column('k_self_calibrated', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_season_id'], ['player_seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pitching_true_talent_player_season_id'), 'pitching_true_talent', ['player_season_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pitching_true_talent_player_season_id'), table_name='pitching_true_talent')
    op.drop_table('pitching_true_talent')
    op.drop_index(op.f('ix_batting_true_talent_player_season_id'), table_name='batting_true_talent')
    op.drop_table('batting_true_talent')
    # ### end Alembic commands ###
